services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_USERNAME:-postgres}
      POSTGRES_USER: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}

volumes:
  pg_data: